# version: '3.8' # Bạn có thể bỏ dòng này nếu Docker Compose của bạn báo warning

services:
  zalo-bot:
    build: .
    container_name: my-zalo-bot-container # Đổi lại tên nếu bạn muốn
    volumes:
      - .:/app 
      - ./session:/app/session 
    restart: unless-stopped 
    environment:
      - NODE_ENV=production
      # - BOT_PORT=3000 # Giá trị mặc định trong bot.js là 3000
    ports: 
      - "9222:9222" # Cho Playwright remote debugging
      - "3000:3000" # Map port của HTTP server trong bot.js ra máy host (dùng sau)
